In [24]:
import tensorflow as tf

In [25]:
tensor = tf.constant([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])
norm_value = tf.norm(tensor, ord=2, axis=[1, 2])
print(norm_value)  # 输出：[5.477225575051661, 14.142135623730951]

tf.Tensor([ 5.4649854 13.190035 ], shape=(2,), dtype=float32)


In [26]:
tensor = tf.constant([[3, 1, 2],[4, 1, 2]])
sorted_tensor = tf.sort(tensor, direction='ASCENDING', axis=0)
sorted_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 1, 2],
       [4, 1, 2]])>

In [27]:
tensor = tf.constant([[3, 1, 2],[0, 5, 2]])
sorted_tensor = tf.argsort(tensor, direction='ASCENDING', axis=1)
sorted_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 0],
       [0, 2, 1]])>

In [57]:
# 创建一个简单的图像张量
image = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 常数填充
tf.pad(image, [[1, 0],[1, 0]], mode='CONSTANT', constant_values=1)
# 对称
tf.pad(image, [[1, 0],[1, 0]], mode='CONSTANT')
# 反射
tf.pad(image, [[1, 0],[1, 0]], mode='REFLECT')

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[5, 4, 5, 6],
       [2, 1, 2, 3],
       [5, 4, 5, 6],
       [8, 7, 8, 9]])>

In [100]:
tensor = tf.constant([-10.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0])
clipped_tensor = tf.clip_by_value(tensor, clip_value_min=-0.5, clip_value_max=1.0)
asd = tf.math.maximum(tf.math.minimum(tensor, 1.0), -0.5)
clipped_tensor,asd# 输出：
# [-0.5, -0.5,  0. ,  0.5,  1. ,  1. ,  1. ]


(<tf.Tensor: shape=(7,), dtype=float32, numpy=array([-0.5, -0.5,  0. ,  0.5,  1. ,  1. ,  1. ], dtype=float32)>,
 <tf.Tensor: shape=(7,), dtype=float32, numpy=array([-0.5, -0.5,  0. ,  0.5,  1. ,  1. ,  1. ], dtype=float32)>)

In [87]:
tensor = tf.constant([1.0, 2.0, 3.0])
t2 = tf.constant([4.0, 5.0, 6.0])
clipped_tensors = tf.clip_by_global_norm([tensor], clip_norm=5.0)
clipped_tensors

([<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>],
 <tf.Tensor: shape=(), dtype=float32, numpy=3.7416575>)

In [101]:
t1 = tf.constant([1.0, 2.0, 3.0])
t2 = tf.constant([4.0, 5.0, 6.0])
t3 = tf.constant([7.0, 6.0, 23.0])
t4 = tf.constant([5.0, 62.0, 51.0])
clipped_tensors, global_norm = tf.clip_by_global_norm([t1, t2,t4,t3], clip_norm=1.0)

clipped_tensors

[<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.01180563, 0.02361125, 0.03541688], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.04722251, 0.05902814, 0.07083376], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.05902814, 0.7319489 , 0.602087  ], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.0826394 , 0.07083376, 0.27152944], dtype=float32)>]

In [105]:
tensor = tf.constant([-1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0])
condition = tf.logical_and(tensor >= -0.5, tensor <= 1.0)
clipped_tensor = tf.where(condition, tensor, tf.constant(-0.5, shape=tensor.shape))
clipped_tensor

<tf.Tensor: shape=(7,), dtype=float32, numpy=array([-0.5, -0.5,  0. ,  0.5,  1. , -0.5, -0.5], dtype=float32)>

In [110]:
x = tf.constant([[10]])
y = tf.constant([[20]])

# 定义两个分支函数
def true_branch():
    return x @ y

def false_branch():
    return x @ y

# 使用 tf.cond
result = tf.cond(x > y, true_branch, false_branch)

print(result)  # 输出：-10

tf.Tensor([[200]], shape=(1, 1), dtype=int32)


In [139]:
# 创建条件张量
condition = tf.constant([True, True, False, False])

# 创建两个张量
x = tf.constant([1, 2, 3, 4])
y = tf.constant([10, 20, 30, 40])

# 使用 tf.where
result = tf.where(condition, x, y)
result

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  2, 30, 40])>