In [2]:
import tensorflow as tf
from tensorflow import keras

In [20]:

with tf.device("/gpu:0"):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])
a.device
b = a.numpy()
tf.is_tensor(b)

False

In [25]:
c = tf.convert_to_tensor(b) #numpy转tensor
tf.is_tensor(c)

True

In [36]:
# 创建一个浮点型 Tensor
tensor_float = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)

# 创建一个整数型 Tensor
tensor_int = tf.constant([[1, 2, 3]], dtype=tf.int32)

In [38]:
tensor_int.numpy()

array([[1, 2, 3]])

In [40]:
tensor_float = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
tensor_int = tf.cast(tensor_float, dtype=tf.int32)

In [42]:
import tensorflow as tf

# 创建一个标量 Tensor
scalar_tensor = tf.constant(5)

# 创建一个一维 Tensor
vector_tensor = tf.constant([1, 2, 3])

# 创建一个二维 Tensor（矩阵）
matrix_tensor = tf.constant([[1, 2], [3, 4]])

# 创建一个三维 Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# 指定数据类型
float_tensor = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)

In [54]:
# 创建一个形状为 [3, 4] 的全零 Tensor
zeros_tensor = tf.zeros([3, 4])
# 创建一个形状为 [2, 2] 的全一 Tensor
ones_tensor = tf.ones([2, 2])

# 指定数据类型
zeros_float = tf.zeros([3, 4], dtype=tf.float32)
ones_int = tf.ones([2, 2], dtype=tf.int32)

In [57]:
# 创建一个形状为 [2, 3] 的 Tensor，填充值为 7
filled_tensor = tf.fill([2, 3], 7)
filled_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7]])>

In [60]:
# 创建一个形状为 [3, 3] 的随机正态分布 Tensor
random_normal = tf.random.normal([3, 3], mean=0.0, stddev=1.0)
random_normal

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.49544033,  1.8233652 , -0.75553036],
       [ 0.2377653 ,  0.21498473,  0.3033026 ],
       [ 0.21892206,  2.672727  , -1.5538156 ]], dtype=float32)>

In [69]:
# 创建一个形状为 [2, 2] 的随机均匀分布 Tensor
random_uniform = tf.random.uniform([2, 2, 3], minval=0, maxval=1)
random_uniform

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0.88991964, 0.07173491, 0.95385635],
        [0.61277795, 0.42028832, 0.66771567]],

       [[0.3431704 , 0.65691864, 0.93220246],
        [0.5058092 , 0.13339126, 0.00436044]]], dtype=float32)>

In [73]:
# 创建一个从 0 到 9 的序列 Tensor
range_tensor = tf.range(10)

# 创建一个从 1 到 10，步长为 2 的序列 Tensor
range_tensor_step = tf.range(1, 11, 2)
range_tensor_step

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [76]:
# 创建一个稀疏 Tensor
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]],  # 稀疏元素的索引
    values=[1, 2],            # 稀疏元素的值
    dense_shape=[3, 4]         # Tensor 的形状
)

In [81]:
# 创建一个一维 Tensor
tensor_1d = tf.constant([1, 2, 3, 4, 5])
tensor_1d

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [83]:
tensor_1d[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [112]:
# 创建一个二维 Tensor
tensor_2d = tf.constant([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

tensor_2d[::3]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [133]:
tensor_3d = tf.constant([[[1, 2], [3, 4], [5, 6], [7, 8]]])

filtered_elements = tf.boolean_mask(tensor_3d[0], tensor_3d[0] > 1)
filtered_elements,tensor_3d[0]

(<tf.Tensor: shape=(7,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7, 8])>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])>)

In [149]:
# 创建一个一维 Tensor
tensor_1d = tf.constant([[10, 20, 30, 40],[10, 20, 30, 40]])

# 提取索引为 [1, 3] 的元素
gathered_elements = tf.gather_nd(tensor_1d, [[0,2],[1,3]])
gathered_elements

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([30, 40])>

In [167]:
# 创建一个二维 Tensor
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])

# 使用 tf.slice 提取从第 1 行到第 2 行的所有列
sliced_tensor = tf.slice(tensor_2d, [0, 0], [1,3])  # 结果为 [[4, 5, 6]]
sliced_tensor

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [179]:
import tensorflow as tf

# 创建一个一维张量
tensor_1d = tf.random.normal([2, 3, 32,22])

# 将一维张量重塑为 2x3 的二维张量
tensor_2d = tf.reshape(tensor_1d, [2, -1])
print(tensor_2d.shape)  # 输出：[[1, 2, 3], [4, 5, 6]]

# 将一维张量重塑为 3x2 的二维张量
tensor_2d = tf.reshape(tensor_1d, [3, -1])
print(tensor_2d.shape)  # 输出：[[1, 2], [3, 4], [5, 6]]

(2, 2112)
(3, 1408)


In [193]:
# 创建一个三维张量
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)
# 调换维度顺序
transposed_tensor = tf.transpose(tensor_3d, perm=[2,0,1])
print(transposed_tensor)
# 输出：
# [[[1, 2], [5, 6]],
#  [[3, 4], [7, 8]]]

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]], shape=(2, 2, 2), dtype=int32)


In [195]:
# 创建一个形状为 [1, 3, 1, 4] 的张量
tensor_4d = tf.constant([[[[1, 2, 3, 4]]]])

# 使用 tf.squeeze 移除大小为 1 的维度
squeezed_tensor = tf.squeeze(tensor_4d)
print(squeezed_tensor.shape)  # 输出：(3, 4)

# 指定移除特定维度
squeezed_tensor = tf.squeeze(tensor_4d, axis=[0, 2])
print(squeezed_tensor.shape)  # 输出：(3, 4)

# 使用 tf.expand_dims 在指定位置插入大小为 1 的维度
expanded_tensor = tf.expand_dims(squeezed_tensor, axis=0)
print(expanded_tensor.shape)  # 输出：(1, 3, 4)

(4,)
(1, 4)
(1, 1, 4)


In [205]:
# 创建两个形状为 [2, 3] 的张量
tensor_a = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor_b = tf.constant([[7, 8, 9], [10, 11, 12]])

# 沿第 0 轴（行）连接
concatenated_tensor = tf.concat([tensor_b,tensor_a], axis=0)
print(concatenated_tensor)
# 输出：
# [[ 1,  2,  3],
#  [ 4,  5,  6],
#  [ 7,  8,  9],
#  [10, 11, 12]]

# 沿第 1 轴（列）连接
concatenated_tensor = tf.concat([tensor_a, tensor_b], axis=1)
print(concatenated_tensor)
# 输出：
# [[ 1,  2,  3,  7,  8,  9],
#  [ 4,  5,  6, 10, 11, 12]]

# 将张量沿第 0 轴分割成两个子张量
tensor_to_split = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
split_tensors = tf.split(tensor_to_split, num_or_size_splits=2, axis=0)
print(len(split_tensors))
# 输出：
# [<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
#  array([[1, 2, 3],
#         [4, 5, 6]], dtype=int32)>,
#  <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
#  array([[ 7,  8,  9],
#         [10, 11, 12]], dtype=int32)>]

tf.Tensor(
[[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)
2


In [213]:
# 创建一个形状为 [2, 3] 的张量
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])

# 沿第 0 轴重复 2 次，沿第 1 轴重复 3 次
tiled_tensor = tf.tile(tensor_2d, multiples=[2, 3])
print(tiled_tensor)
# 输出：
# [[1, 2, 3, 1, 2, 3, 1, 2, 3],
#  [4, 5, 6, 4, 5, 6, 4, 5, 6],
#  [1, 2, 3, 1, 2, 3, 1, 2, 3],
#  [4, 5, 6, 4, 5, 6, 4, 5, 6]]

tf.Tensor(
[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]], shape=(4, 9), dtype=int32)


In [224]:
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])
# 这里进行了隐式的转换
tensor_2d + tensor_2d[0,1]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]])>

In [5]:
import numpy as np

# 定义两个三维数组
a = np.random.rand(2, 3, 4)
b = np.random.rand(2, 4, 5)

In [19]:

x = tf.constant(5)
y = tf.constant(3)
result_pow = tf.pow(x, y)  # 125
result_pow,x**y

(<tf.Tensor: shape=(), dtype=int32, numpy=125>,
 <tf.Tensor: shape=(), dtype=int32, numpy=125>)

In [22]:
x = tf.constant(5)
y = tf.constant(3)

# 等于
result_equal = tf.equal(x, y)  # False

# 不等于
result_not_equal = tf.not_equal(x, y)  # True

# 小于
result_less = tf.less(x, y)  # False

# 小于等于
result_less_equal = tf.less_equal(x, y)  # False

# 大于
result_greater = tf.greater(x, y)  # True

# 大于等于
result_greater_equal = tf.greater_equal(x, y)  # True

In [25]:
x = tf.constant(True)
y = tf.constant(False)

# 逻辑与
result_and = tf.logical_and(x, y)  # False

# 逻辑或
result_or = tf.logical_or(x, y)  # True

# 逻辑非
result_not = tf.logical_not(x)  # False

In [28]:
x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[5, 6], [7, 8]])

# 矩阵乘法
result_matmul = tf.matmul(x, y)  # [[19, 22], [43, 50]]
result_matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [29]:
x = tf.constant([-1.0, 0.0, 1.0])

# ReLU 激活函数
result_relu = tf.nn.relu(x)  # [0.0, 0.0, 1.0]

# Sigmoid 激活函数
result_sigmoid = tf.nn.sigmoid(x)  # [0.2689, 0.5, 0.7311]

# Tanh 激活函数
result_tanh = tf.nn.tanh(x)  # [-0.7616, 0.0, 0.7616]